services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mipyme_db
      POSTGRES_USER: mipyme_user
      POSTGRES_PASSWORD: MiP4ssw0rd_S3gur0_2025!
    ports: ["5432:5432"]
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: ../backend
    env_file: ../backend/.env
    depends_on: [db]
    ports: ["8000:8000"]
    volumes:
      - ../backend:/app

volumes:
  db: {}
